services:   ##הגדרת רשימה של שירותים (קונטיינרים) להרצה##
  app:    ##שם השירות שתחת הSERVICE##
    build: .   ##בניית תמונה חדשה##
    ports:      
      - "5000:5000"   ##פתיחת פורט##
  redis:       ##שם השירות השני##
    image: redis    ##שימוש בתמונה קיימת##